#Secret
apiVersion: v1
data:
  DB: ZGV2b3Bz
  DB_HOST: ZGV2b3BzLW1vbmdvZGItc2VydmljZToyNzAxNw==
  DB_PASS: VGVzdDEyMw==
  DB_USER: bW9uZ29kYg==
kind: Secret
metadata:
  name: mongo-conection-secret
  namespace: chaos-space

---
#API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-tools-api
  name: devops-tools-api
  namespace: chaos-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-tools-api
  template:
    metadata:
      labels:
        app: devops-tools-api
    spec:
      containers:
      - image: gashers82/devops-tools-api:1.0.0-pm2
        name: devops-tools-api
        envFrom:
        - secretRef:
            name: mongo-conection-secret

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-tools-api
  name:  devops-tools-api-service
  namespace: chaos-space
spec:
  ports:
  - port: 3000 
    protocol: TCP
    targetPort: 3000
    nodePort: 30080
  selector:
    app: devops-tools-api
  type: NodePort
status:
  loadBalancer: {}