apiVersion: v1
data:
  DB: ZGV2b3Bz
  DB_HOST: ZGV2b3BzLW1vbmdvZGItc2VydmljZToyNzAxNw==
  DB_PASS: VGVzdDEyMw==
  DB_USER: bW9uZ29kYg==
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo-conection-secret
