apiVersion: v1
kind: Service
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  ports:
  - port: 3000 
    protocol: TCP
    targetPort: 3000
    nodePort: 30080
  selector:
    run: frontend
  type: NodePort
status:
  loadBalancer: {}
